# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dadd21e74c6c6d633c3d1b1a1194004227a574c500e9a7686203d42479d7ea807b3b34a2079a4c08a1e8f84735a976c08ce1c9ff14a39ef4c90347420f1130dd

test:
  secret_key_base: 22ffd1269adcd60bff4b278f058ee580aeab5635d285bd36da8eae14a3d41775b4a86f0ceb820152a3b0a181024bad445bc14d5a656e66c23c0db371603b7b22

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
